brand: ['packages/source/brand']
foundations: ['packages/source/foundations']
icons: ['packages/source/icons']
accordion: ['packages/source/components/accordion']
button: ['packages/source/components/button']
checkbox: ['packages/source/components/checkbox']
choice card: ['packages/source/components/choice-card']
footer: ['packages/source/components/footer']
label: ['packages/source/components/label']
layout: ['packages/source/components/layout']
link: ['packages/source/components/link']
radio: ['packages/source/components/radio']
select: ['packages/source/components/select']
text area: ['packages/source/components/text-area']
text input: ['packages/source/components/text-input']
user feedback: ['packages/source/components/user-feedback']
