export const labels: Record<string, string> = {
	'alert-round': 'Warning',
	'alert-triangle': 'Warning',
	'apple-brand': 'Apple logo',
	'arrow-down-straight': 'Arrow down',
	'arrow-left-straight': 'Arrow left',
	'arrow-right-straight': 'Arrow right',
	'arrow-up-straight': 'Arrow up',
	audio: 'Audio',
	camera: 'Camera',
	checkmark: 'Checkmark',
	'chevron-down-single': 'Expand to show more',
	'chevron-left-double': 'Double chevron left',
	'chevron-left-single': 'Chevron left',
	'chevron-right-double': 'Double chevron right',
	'chevron-right-single': 'Chevron right',
	'chevron-up-single': 'Collapse to show less',
	clock: 'Clock',
	'credit-card': 'Credit card',
	cross: 'Close',
	'crossed-out-cloud': 'No wifi',
	'direct-debit': 'Direct Debit logo',
	'direct-debit-wide': 'Direct Debit logo',
	envelope: 'Email',
	exclamation: 'Exclamation mark',
	external: 'External link',
	eye: 'View',
	'eye-strike': 'Not visible',
	facebook: 'Facebook logo',
	'facebook-brand': 'Facebook logo',
	'facebook-messenger': 'Facebook Messenger logo',
	gift: 'Gift',
	globe: 'Globe',
	'google-brand': 'Google logo',
	house: 'Home',
	indent: 'Indent',
	'info-round': 'Information',
	'linked-in': 'LinkedIn logo',
	'media-controls-play': 'Play',
	minus: 'Minus sign',
	'pay-pal-brand': 'PayPal logo',
	person: 'Account',
	pinned: 'Pinned',
	pinterest: 'Pinterest logo',
	plus: 'Plus sign',
	quote: 'Quote',
	settings: 'Settings',
	'speech-bubble': 'Comments',
	spinner: 'Comments',
	star: 'Star',
	'tick-round': 'Ticked',
	twitter: 'Twitter logo',
	video: 'Video',
	'whats-app': 'WhatsApp logo',
};
