import { neutral, error, brand } from "./global"

export const text = {
	primary: neutral[7],
	secondary: neutral[46],
	error: error[400],
	buttonPrimary: neutral[100],
	buttonSecondary: brand[400],
	checkbox: neutral[7],
	checkboxSupporting: neutral[46],
	checkboxIndeterminate: neutral[46],
	linkPrimary: brand[500],
	linkPrimaryHover: brand[500],
	linkSecondary: neutral[7],
	linkSecondaryHover: neutral[7],
	radio: neutral[7],
	radioSupporting: neutral[46],
	textInput: neutral[7],
	brand: {
		primary: neutral[100],
		secondary: brand[800],
		error: error[500],
		buttonPrimary: brand[400],
		buttonSecondary: neutral[100],
		checkbox: neutral[100],
		checkboxSupporting: brand[800],
		checkboxIndeterminate: brand[800],
		linkPrimary: neutral[100],
		linkPrimaryHover: neutral[100],
		radio: neutral[100],
		radioSupporting: brand[800],
	},
	brandYellow: {
		primary: neutral[7],
		secondary: neutral[60],
		buttonPrimary: neutral[100],
		buttonSecondary: neutral[7],
		linkPrimary: neutral[7],
		linkPrimaryHover: neutral[7],
	},
}
