import { promises } from 'fs';
import path from 'path';
import mkdirp from 'mkdirp';
import { createIconComponent } from './create-icon-component';
import { createReadme } from './create-readme';
import { getIconsFromFigma } from './get-svgs-from-figma';

const { writeFile, rm } = promises;

// most icons are the same and can be run through the component generator
// but some are different and need to be handled separately
const SPECIAL_CASES = {
	retainFill: [
		'apple-brand',
		'facebook-brand',
		'google-brand',
		'pay-pal-brand',
	],
	isWide: ['direct-debit-wide'],
};

const VENDOR_ICON_PATH = path.resolve(__dirname, '..', 'vendor', 'icons');

const warning = [
	'// DO NOT EDIT',
	'// this file is auto-generated by packages/@guardian/source-react-components/scripts/create-icons/index.ts',
	'',
].join('\n');

// now we start fetching SVGs and building our components
void (async () => {
	// remove any existing icons from a previous run
	try {
		await rm(VENDOR_ICON_PATH, { recursive: true });
	} catch (e) {
		// do nothing
	}

	// create the icons directory
	await mkdirp(VENDOR_ICON_PATH);

	// create a readme
	await writeFile(
		path.resolve(VENDOR_ICON_PATH, 'README.md'),
		createReadme(),
		'utf8',
	);

	const icons = await getIconsFromFigma();

	// fetch the SVGs from Figma, create a react component from them using svgr
	// and save them both
	for (const icon of icons) {
		const component = await createIconComponent({
			icon,
			retainFill: SPECIAL_CASES.retainFill.includes(icon.name),
			isWideIcon: SPECIAL_CASES.isWide.includes(icon.name),
		});

		await writeFile(
			path.resolve(VENDOR_ICON_PATH, `${icon.name}.svg`),
			warning + icon.svg,
			'utf8',
		);

		await writeFile(
			path.resolve(VENDOR_ICON_PATH, `${icon.name}.tsx`),
			warning + component,
			'utf8',
		);
	}
})();
