export const labels: Record<string, string> = {
	'alert-phone': 'Mobile phone with exclamation mark',
	'alert-round': 'Warning',
	'alert-triangle': 'Warning',
	'apple-brand': 'Apple logo',
	'arrow-contract': 'Collapse',
	'arrow-down-straight': 'Arrow down',
	'arrow-expand': 'Expand',
	'arrow-left-straight': 'Arrow left',
	'arrow-outdent': 'Up left arrow',
	'arrow-pop-out': 'Pop out',
	'arrow-right-straight': 'Arrow right',
	'arrow-scroll': 'Scroll content',
	'arrow-up-and-down-small': 'Up and down arrow',
	'arrow-up-straight-small': 'Arrow up',
	'arrow-up-straight': 'Arrow up',
	asterisk: 'Asterisk',
	audio: 'Audio',
	'audio-mute': 'Sound off',
	'book-mark': 'Bookmark',
	'book-mark-cross': 'Remove bookmark',
	calendar: 'Calendar',
	camera: 'Camera',
	checkmark: 'Checkmark',
	'chevron-down-double': 'Double chevron down',
	'chevron-down-single': 'Expand to show more',
	'chevron-down-single-xsmall': 'Expand to show more',
	'chevron-left-double': 'Double chevron left',
	'chevron-left-single': 'Chevron left',
	'chevron-right-double': 'Double chevron right',
	'chevron-right-single': 'Chevron right',
	'chevron-up-double': 'Double chevron up',
	'chevron-up-single': 'Collapse to show less',
	clock: 'Clock',
	'clock-baseline-small': 'Clock',
	'credit-card': 'Credit card',
	cross: 'Close',
	'cross-round': 'Close',
	crosswords: 'Crosswords',
	'crossed-out-cloud': 'No wifi',
	'direct-debit': 'Direct Debit logo',
	'direct-debit-wide': 'Direct Debit logo',
	document: 'Document',
	download: 'Download',
	'drag-handle': 'Drag',
	edit: 'Edit',
	ellipsis: 'More',
	envelope: 'Email',
	exclamation: 'Exclamation mark',
	external: 'External link',
	eye: 'View',
	'eye-strike': 'Not visible',
	facebook: 'Facebook logo',
	'facebook-brand': 'Facebook logo',
	'facebook-messenger': 'Facebook Messenger logo',
	filter: 'Filter',
	gift: 'Gift',
	globe: 'Globe',
	'google-brand': 'Google logo',
	gps: 'Location',
	'hand-pointed': 'Interactive',
	house: 'Home',
	'house-cross': 'Remove from home',
	'house-plus': 'Add to home',
	'house-setting': 'Settings',
	indent: 'Indent',
	'info-round': 'Information',
	'linked-in': 'LinkedIn logo',
	'location-marker': 'Location',
	'magnifying-glass': 'Search',
	'magnifying-glass-minus': 'Zoom out',
	'magnifying-glass-plus': 'Zoom in',
	'magnifying-glass-sad-face': 'No results',
	'media-controls-back': 'Rewind',
	'media-controls-forward': 'Fast forward',
	'media-controls-pause': 'Pause',
	'media-controls-stop': 'Stop',
	'media-controls-play': 'Play',
	menu: 'Menu',
	minus: 'Minus sign',
	moon: 'Dark mode',
	newsletter: 'Newsletter',
	'notifications-off': 'Notification off',
	'notifications-on': 'Notification on',
	padlock: 'Lock',
	'party-of-three': 'Share',
	'pay-pal-brand': 'PayPal logo',
	'person-cross': 'Remove user',
	'person-plus': 'Add user',
	'person-round': 'Account',
	'person-tick': 'Verified user',
	person: 'Account',
	phone: 'Mobile phone',
	pinned: 'Pinned',
	pinterest: 'Pinterest logo',
	plus: 'Plus sign',
	quote: 'Quote',
	reload: 'Reload',
	settings: 'Settings',
	share: 'Share',
	'speech-bubble': 'Comments',
	'speech-bubble-cross': 'Remove comment',
	'speech-bubble-plus': 'Add comment',
	spinner: 'Comments',
	star: 'Star',
	'star-outline': 'Star outline',
	'text-large': 'Large text',
	'text-size': 'Text size',
	'text-small': 'Small text',
	'tick-round': 'Ticked',
	twitter: 'Twitter logo',
	upload: 'Upload',
	video: 'Video',
	'whats-app': 'WhatsApp logo',
};
