name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'pnpm'
      - name: build
        run: |
          pnpm install --frozen-lockfile
          pnpm build:storybook
      - name: deploy
        run: pnpm storybook-to-ghpages --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
