name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build:storybook
      - name: deploy
        run: yarn storybook-to-ghpages --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
