name: ESLint Plugin Integration Tests
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - '[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build:eslint
      - run: rm -rf ./scripts/eslint-integration-test/node_modules
      - run: yarn install --frozen-lockfile
      - run: yarn workspace eslint-integration-test test
