name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true # remove redundant labels after a change
